const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const os = require('node:os');
const {chromium} = require('playwright');
const C = require('../docs/finemtec-core.js');
const docs = path.resolve(__dirname, '../docs');
const artifacts = process.env.VANTAGE_TEST_ARTIFACTS || path.join(os.tmpdir(), 'vantage-finemtec-qa');
fs.mkdirSync(artifacts, {recursive: true});
assert.throws(() => C.parsePoints('2026-02-30,2'));
assert.throws(() => C.parsePoints('2026-01-01,2\n2026-01-01,3'));
assert.deepEqual(C.parsePoints('2026-02-01,0\n2026-01-01,-1').map(p => p.value), [-1, 0]);
assert.deepEqual(C.normalize([{value:-20},{value:null},{value:10}]).map(p=>p.value), [0,null,100]);
assert.deepEqual(C.normalize([{value:4},{value:4}]).map(p=>p.value), [50,50]);
const server = http.createServer((req, res) => {
  const pathname = new URL(req.url, 'http://localhost').pathname;
  const target = path.resolve(docs, '.' + decodeURIComponent(pathname));
  if (!target.startsWith(docs + path.sep) || !fs.existsSync(target) || !fs.statSync(target).isFile()) {res.writeHead(404); res.end(); return;}
  const types = {'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};
  res.setHeader('Content-Type', types[path.extname(target)] || 'application/octet-stream');
  fs.createReadStream(target).pipe(res);
});
(async () => {
  let browser;
  try {
    await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
    browser=await chromium.launch({headless:true,channel:'msedge'});
    const context=await browser.newContext({viewport:{width:1440,height:1120},reducedMotion:'reduce'});
    const page=await context.newPage();
    const errors=[];
    page.on('pageerror', e=>errors.push(e.message));
    await page.goto(`http://127.0.0.1:${server.address().port}/datahub.html`);
    await page.locator('#__gate_input').fill('1011');await page.locator('#__gate_btn').click();
    await page.waitForSelector('[data-series="price"]');
    assert.match(await page.locator('.fm-quote').innerText(),/8,290/);
    assert.equal(await page.locator('#fm-select-financial').getAttribute('open'),null);
    await page.locator('#fm-select-financial summary').click();
    await page.locator('[data-metric="opm"]').check();
    await page.waitForSelector('[data-series="opm"]');
    await page.locator('[data-range="1Y"]').click();
    await page.locator('#fm-select-trade summary').click();
    assert.equal(await page.locator('[data-metric="trade_value"]').isDisabled(),true);
    assert.match(await page.locator('.fm-availability').innerText(),/0이라는 뜻은 아닙니다/);
    await page.locator('#fm-mode').selectOption('normalized');
    assert.match(await page.locator('#fm-axis-note').innerText(),/최솟값/);
    await page.locator('#fm-hit').focus();await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#fm-tooltip').isVisible(),true);
    await page.keyboard.press('Escape');
    await page.locator('#fm-add-custom').click();
    await page.locator('[name="name"]').fill('테스트 <출하량>');
    await page.locator('[name="points"]').fill('2026-07-31,100\n2026-08-31,120');
    await page.locator('#fm-custom-form [type="submit"]').click();
    await page.waitForSelector('[data-series^="custom-"]');
    assert.equal(await page.locator('출하량').count(),0);
    await page.reload();await page.waitForSelector('[data-series^="custom-"]');
    await page.locator('#fm-select-financial summary').click();
    await page.locator('[data-delete-custom]').click();
    assert.equal(await page.locator('[data-series^="custom-"]').count(),0);
    await page.locator('#company-search').fill('삼성전자');await page.locator('#company-apply').click();
    assert.equal(await page.locator('#finemtec-workspace').isVisible(),false);
    await page.locator('#company-search').fill('441270');await page.locator('#company-apply').click();
    await page.waitForSelector('[data-series="price"]');
    await page.locator('.workbench').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(artifacts,'desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    await page.waitForTimeout(250);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
    await page.locator('#fm-select-financial summary').click();
    await page.locator('.fm-hero').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(artifacts,'mobile.png'),fullPage:true});
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({result:'PASS',checks:['financial toggles','period range','missing trade disabled','normalized axes','keyboard tooltip','custom add/persist/delete','escaped label','company navigation','mobile overflow','no page errors'],artifacts}));
    await context.close();
  } finally {if(browser)await browser.close();server.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
